# Task 1

## Conceptual Questions

### 1.	Why is Python preferred in the field of Data Science?

  Python is preffered in datasciences because of easy syntax ,more libraries and more in-built function.Libraries like pandas and matplot makes easier to analyse and visualize the data.It is also used in machine learning and deep learning analysis.

### 2.	What is the difference between a Jupyter Notebook and Google Colab?

Jupyter notebook runs in local host and Google Colab is a cloud based platform.Both has their own libraries and syntax ,if it is a sensitive data and the dataset occupies less space we can opt for jupyter notebook,for dealing with large dataset and deeplearning projects we can opt for google colab since it requires more GPU.

### 3.	When would you use a list over a set or a tuple?

In the future if the client need to manipulate the data like adding,removing and updating we can use list,slicing and indexing is possible in list whereas in tuple we can't update the dataset and in set the data is not ordered .

### 4.	What is exception handling? Give a real-life example of when it's useful.

Exception handling helps to handle runtime errors without crashing the entire program and execution of the program .For example in number guessing game if the user enter any other character other than number it will show valueerror ,using try except we can display a message to enter the correct number without crashing the execution of the program

### 5.	Define DataFrame and Series in Pandas. What’s the difference?

A series is a one dimensional index based array in pandas where data is stored in single column whereas dataframe is two dimensional array stored in rows and columns.A dataframe has multiple series where each column is considered as series

### 6.	What are the different ways of dealing with missing values in a dataset?

The first step is to inform the client and try to retrieve the data from client.If it is not possible to retrieve ,we can compare the similar the data with other data and we can impute the values.Also by using mean,mode we can impute the missing values

### 7.	How do NumPy and Pandas differ in terms of functionality?

Numpy is mainly used for numerical computation of homogenous data,Pandas is used for analysis of heterogenoues datas

### 8.	What is the role of libraries like Seaborn and Matplotlib in a data project?

Seaborn and Matplotlib are used for data visualization using charts like bar chart,histogram,line charts,piecharts etc.Ity helps the analyst to analyse the trend of a business

### 9.	When should you use .loc[] and when .iloc[]?

.loc[] is used for label based indexing where rows and columns can be accessed by their names. iloc[] is based on interger position indexing here rows and columns can be accessed by their row number/column number

### 10.	What is the importance of writing functions in Python?

Functions are important in python because it helps to avoid code repition and improve code reusability.A specific task can be wriiten under a single functiona and it cam be reused multiple times whenever needed.It makes the program more readable and easier to debug.

## Scripting based question

### 1.	Write a program to take a name and age from the user and print a greeting message.

In [6]:
Name=input("Enter the Name:")
Age=input("Enter the Age:")
print("Welcome {} & your age is {}".format(Name,Age))

Enter the Name: Dhivan
Enter the Age: 25

Welcome Dhivan & your age is 25

### 2.	Create a list of numbers and print only even numbers using a for loop.

In [13]:
Even_list=[]
for i in range(1,50):
    if i%2==0:
        Even_list.append(i)
print("The Even Numbers are",Even_list)

The Even Numbers are [2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42, 44, 46, 48]

### 3.	Write a program that handles division by zero using try-except.

In [19]:
Numerator=int(input("Enter the numerator"))
Denominator=int(input("Enter the denominator"))
try:
    if Numerator%Denominator==0:
        print("No Remainder")
except ZeroDivisionError:
    print("Enter values other than Zero")

Enter the numerator 5
Enter the denominator 0

Enter values other than Zero

### 4.	Given a string, count how many vowels it has

In [32]:
sentence=input("Enter word/sentence:").lower()
count=0
for character in sentence:
    if character in "aeiou":
        count+=1
print("The total no of vowels are",count)

Enter word/sentence: Hi Hello I am Dhivan

The total no of vowels are 7

### 5.	Reverse a list without using built-in functions.

In [42]:
list=[1,2,3,4,5]
i=len(list)-1
reverse=[]
while i>=0:
    reverse.append(list[i])
    i=i-1
print(reverse)

[5, 4, 3, 2, 1]

### 6.	Create a dictionary with at least 5 key-value pairs and print them.

In [46]:
import pandas as pd
Snacks_details=pd.DataFrame(data={"Snacks":["Tea","Biscuits","Samosa","Pancakes","BananaCake"],
                   "Quantity":[4,5,8,6,10],
                   "Price":[35,40,20,60,30],
                  "ValueAdded":["Yes","Yes","Yes","Yes","Yes"],
                   "Rating":[5,3,1,5,5],
                    "Recommended":["Yes","No","No","Yes","Yes"]
                  })
Snacks_details

       Snacks  Quantity  Price ValueAdded  Rating Recommended
0         Tea         4     35        Yes       5         Yes
1    Biscuits         5     40        Yes       3          No
2      Samosa         8     20        Yes       1          No
3    Pancakes         6     60        Yes       5         Yes
4  BananaCake        10     30        Yes       5         Yes

### 7.	Write a Pandas code to read a CSV and print the top 5 rows.

In [1]:
import pandas as pd
emp_data=pd.read_csv("employee_data.csv").head()
emp_data

      Name   Age Department   Salary   Join_Date
0   Rajesh  29.0        Ops  60000.0  21-05-2023
1    Nasir  31.0    IT Tech      NaN  12-11-2020
2  Mathiew   NaN    Support  58000.0  15-01-2025
3  Gilbert  29.0        Ops  60000.0  21-05-2021
4    Kevin  28.0    Support  61000.0  30-07-2024

### 8. Create a DataFrame from a Python dictionary.

In [50]:
import pandas as pd
Snacks_details=pd.DataFrame(data={"Snacks":["Tea","Biscuits","Samosa","Pancakes","BananaCake"],
                   "Quantity":[4,5,8,6,10],
                   "Price":[35,40,20,60,30],
                  "ValueAdded":["Yes","Yes","Yes","Yes","Yes"],
                   "Rating":[5,3,1,5,5],
                    "Recommended":["Yes","No","No","Yes","Yes"]
                  })
Snacks_details

       Snacks  Quantity  Price ValueAdded  Rating Recommended
0         Tea         4     35        Yes       5         Yes
1    Biscuits         5     40        Yes       3          No
2      Samosa         8     20        Yes       1          No
3    Pancakes         6     60        Yes       5         Yes
4  BananaCake        10     30        Yes       5         Yes

### 9.	Replace all missing values in a DataFrame with the column’s mean.

In [1]:
emp_data["Salary"]=emp_data["Salary"].mean()
emp_data

NameError: name 'emp_data' is not defined

### 10.	Filter rows in a DataFrame where the "Age" column is greater than 30.

In [70]:
emp_data[emp_data["Age"]>29]

    Name   Age Department   Salary   Join_Date
1  Nasir  31.0    IT Tech  52000.0  12-11-2020